const products = [
  { id: 1, name: "Hair Oil", src: "gallery/product1.jpeg" },
  { id: 2, name: "Harpic", src: "gallery/product2.jpeg" },
  { id: 3, name: "Odonil", src: "gallery/product3.jpeg" },
  { id: 4, name: "Hamam Soap", src: "gallery/product4.jpeg" },
  { id: 5, name: "5 Star", src: "gallery/product5.jpeg" },
  { id: 6, name: "3 Roses", src: "gallery/product6.jpeg" },
  { id: 7, name: "Johnson's Baby Soap", src: "gallery/product7.jpeg" },
  { id: 8, name: "Center Fresh", src: "gallery/product8.jpeg" },
  { id: 9, name: "Shakthi Masala", src: "gallery/product9.jpeg" },
  { id: 10, name: "Oreo", src: "gallery/product10.jpeg" },
  { id: 11, name: "Comfort", src: "gallery/product11.jpeg" },
  { id: 12, name: "Closeup", src: "gallery/product12.jpeg" },
  { id: 13, name: "Nippon Paint", src: "gallery/product13.jpeg" },
  { id: 14, name: "Apsara Pencils", src: "gallery/product14.jpeg" },
  { id: 15, name: "Vicks", src: "gallery/product15.jpeg" },
  { id: 16, name: "Aachi Pickle", src: "gallery/product16.jpeg" },
  { id: 17, name: "Fortune Sunflower oil", src: "gallery/product17.jpeg" },
  { id: 18, name: "Arokya Milk", src: "gallery/product18.jpeg" },
  { id: 19, name: "7up", src: "gallery/product19.jpeg" },
  { id: 20, name: "Gulab Jamun Mix", src: "gallery/product20.jpeg" },
  { id: 21, name: "Vasanth & Co", src: "gallery/product21.jpeg" },
  { id: 22, name: "Campa", src: "gallery/product22.jpeg" },
  { id: 23, name: "Colgate", src: "gallery/product23.jpeg" },
  { id: 24, name: "Tata Glucose", src: "gallery/product24.jpeg" },
  { id: 25, name: "Mamypoko Pants", src: "gallery/product25.jpeg" },
  { id: 26, name: "Dindigul Thalapakatti", src: "gallery/product26.jpeg" },
  { id: 27, name: "Act 2 Popcorn", src: "gallery/product27.jpeg" },
  { id: 28, name: "Lakme Iconic Kajal", src: "gallery/product28.jpeg" },
  { id: 29, name: "Udhaya Krishna Ghee", src: "gallery/product29.jpeg" },
  { id: 30, name: "Boost", src: "gallery/product30.jpeg" },
  { id: 31, name: "Fair & Lovely", src: "gallery/product31.jpeg" },
  { id: 32, name: "Clinic Plus", src: "gallery/product32.png" },
  { id: 33, name: "Nutella", src: "gallery/product33.png" },
  { id: 34, name: "Ujala", src: "gallery/product34.png" },
  { id: 35, name: "Gillette Razor", src: "gallery/product35.png" },
  { id: 36, name: "HIT Mosquito Repellent", src: "gallery/product36.png" },
  { id: 37, name: "FOGG", src: "gallery/product37.png" },
  { id: 38, name: "Bingo", src: "gallery/product38.png" },
  { id: 39, name: "Gems Chocolates", src: "gallery/product39.png" },
  { id: 40, name: "Arasan Soaps", src: "gallery/product40.png" },
  { id: 41, name: "Complan", src: "gallery/product41.png" },
  { id: 42, name: "Pedigree", src: "gallery/product42.png" },
  { id: 43, name: "Face wash", src: "gallery/product43.png" },
  { id: 44, name: "Ferrero Rocher", src: "gallery/product44.png" },
  { id: 45, name: "Mercely's Ice Cream", src: "gallery/product45.png" },
  { id: 46, name: "Kissan Peanut Butter", src: "gallery/product46.png" },
  { id: 47, name: "Muscleblaze Protein Bar", src: "gallery/product47.png" },
  { id: 48, name: "Sowbhagya Wet grinder", src: "gallery/product48.png" },
  { id: 49, name: "Prestige Cooker", src: "gallery/product49.png" },
  { id: 50, name: "Kinder Joy", src: "gallery/product50.png  " },
];
